server:
  port: 8090
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''

  config:
    import:
      - "application_qa.yml"
      - "application_pro.yml"
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "3.0"

loans:
  message: "Welcome to EZ Bank Loans related  APIs"
  contactDetails:
    name: "tintrongthai"
    email: "john@eazybank.com"
  onCallSupport:
    - 0364329047