server:
  port: 8090
  error:
    include-stacktrace: never
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3307/loansdb
#
#    username: root
#    password: admin123

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    h2:
      console:
        enabled: true
  config:
    import: "optional:configserver:http://localhost:8071/"

  profiles:
    active: "pro"

  sql:
    init:
      mode: always
  jpa:

    show-sql: true
  application:
    name: "loans"



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "Eazy Bank loans Application"
    version: "1.0"