server:
  port: 8090
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb

    username: root
    password: admin123

  config:
    import: "optional:configserver:http://localhost:8071/"

  profiles:
    active: "pro"

  sql:
    init:
      mode: always
  jpa:

    show-sql: true
  application:
    name: "loans"


management:
  endpoints:
    web:
      exposure:
        include: "*"